spring.application.name=vantage-bank

# 1. Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/vantage
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 2. JPA Settings (Standard)
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql=true

# 3. Schema Management
spring.jpa.hibernate.ddl-auto=validate

# JWT Configuration
# This is a 256-bit encryption key
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000