spring.application.name=vantage-bank

# 1. Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/vantage
spring.datasource.username=postgres
spring.datasource.password=root

# 2. JPA Settings (Standard)
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql=true

# 3. Schema Management
spring.jpa.hibernate.ddl-auto=validate